// AUTO-GENERATED by scripts/ts/generate-auto-module-bindings.ts
// Do not edit manually. Run: npm run generate-auto-module-bindings

import {
  GetPromisedRPCTypeSignaturesForClazz,
  bindMethodNamesAsRPCs
} from "src/scripting/modules/shared/rpcContract";
import { moduleAPIFromRunner } from "src/scripting/runtime/SpellWorkerModuleAPI";
import type { JSRunnerAPI } from "src/scripting/core/api";
import type AimNative from "src/scripting/modules/auto/Aim.native";
import type AirNative from "src/scripting/modules/auto/Air.native";
import type AreaPreviewNative from "src/scripting/modules/auto/AreaPreview.native";
import type EarthBlockNative from "src/scripting/modules/auto/EarthBlock.native";
import type FireNative from "src/scripting/modules/auto/Fire.native";
import type GetEntitiesNative from "src/scripting/modules/auto/GetEntities.native";
import type GrappleNative from "src/scripting/modules/auto/Grapple.native";
import type HealNative from "src/scripting/modules/auto/Heal.native";
import type IceBlockNative from "src/scripting/modules/auto/IceBlock.native";
import type PingNative from "src/scripting/modules/auto/Ping.native";
import type PlayerControlsNative from "src/scripting/modules/auto/PlayerControls.native";
import type PlayerInventoryNative from "src/scripting/modules/auto/PlayerInventory.native";
import type ProjectileNative from "src/scripting/modules/auto/Projectile.native";
import type SensorNative from "src/scripting/modules/auto/Sensor.native";
import type SparkNative from "src/scripting/modules/auto/Spark.native";
import type SpeedNative from "src/scripting/modules/auto/Speed.native";
import type SpellsNative from "src/scripting/modules/auto/Spells.native";
import type TabsNative from "src/scripting/modules/auto/Tabs.native";
import type TerrainNative from "src/scripting/modules/auto/Terrain.native";

/**
 * The pseudo-side RPC-proxy map, keyed identically to autoNativeBindings.
 * Each value forwards calls to the matching native handler over nativeRPC.
 */
export type AutoPseudoBindings = {
  AimNative: GetPromisedRPCTypeSignaturesForClazz<AimNative>;
  AirNative: GetPromisedRPCTypeSignaturesForClazz<AirNative>;
  AreaPreviewNative: GetPromisedRPCTypeSignaturesForClazz<AreaPreviewNative>;
  EarthBlockNative: GetPromisedRPCTypeSignaturesForClazz<EarthBlockNative>;
  FireNative: GetPromisedRPCTypeSignaturesForClazz<FireNative>;
  GetEntitiesNative: GetPromisedRPCTypeSignaturesForClazz<GetEntitiesNative>;
  GrappleNative: GetPromisedRPCTypeSignaturesForClazz<GrappleNative>;
  HealNative: GetPromisedRPCTypeSignaturesForClazz<HealNative>;
  IceBlockNative: GetPromisedRPCTypeSignaturesForClazz<IceBlockNative>;
  PingNative: GetPromisedRPCTypeSignaturesForClazz<PingNative>;
  PlayerControlsNative: GetPromisedRPCTypeSignaturesForClazz<PlayerControlsNative>;
  PlayerInventoryNative: GetPromisedRPCTypeSignaturesForClazz<PlayerInventoryNative>;
  ProjectileNative: GetPromisedRPCTypeSignaturesForClazz<ProjectileNative>;
  SensorNative: GetPromisedRPCTypeSignaturesForClazz<SensorNative>;
  SparkNative: GetPromisedRPCTypeSignaturesForClazz<SparkNative>;
  SpeedNative: GetPromisedRPCTypeSignaturesForClazz<SpeedNative>;
  SpellsNative: GetPromisedRPCTypeSignaturesForClazz<SpellsNative>;
  TabsNative: GetPromisedRPCTypeSignaturesForClazz<TabsNative>;
  TerrainNative: GetPromisedRPCTypeSignaturesForClazz<TerrainNative>;
};

export function buildAutoPseudoBindings(
  runner: JSRunnerAPI
): AutoPseudoBindings {
  const rpcFor =
    (moduleName: string) =>
    (data: unknown): Promise<unknown> => {
      const moduleAPI = moduleAPIFromRunner(runner);
      if (!moduleAPI) {
        throw new Error(
          "Cannot dispatch native RPC: module API not attached to this runner."
        );
      }
      return moduleAPI.nativeRPC(moduleName, data);
    };
  const bindings = {} as AutoPseudoBindings;
  const AimNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<AimNative>>(rpcFor("AimNative"), ["_switchLevel", "aim", "aimRelative", "init", "teardown"]);
  bindings.AimNative = AimNativeRpcs;
  const AirNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<AirNative>>(rpcFor("AirNative"), ["applyAirBurst"]);
  bindings.AirNative = AirNativeRpcs;
  const AreaPreviewNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<AreaPreviewNative>>(rpcFor("AreaPreviewNative"), ["createPreview", "destroyPreview", "recolorPreview"]);
  bindings.AreaPreviewNative = AreaPreviewNativeRpcs;
  const EarthBlockNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<EarthBlockNative>>(rpcFor("EarthBlockNative"), ["castEarthBlockSync", "destroyEarthBlock", "detachEarthBlock", "teardown"]);
  bindings.EarthBlockNative = EarthBlockNativeRpcs;
  const FireNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<FireNative>>(rpcFor("FireNative"), ["createBlast", "createFireball", "createFirewave", "explodeFireball", "moveFireballTo", "setFireballVelocity"]);
  bindings.FireNative = FireNativeRpcs;
  const GetEntitiesNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<GetEntitiesNative>>(rpcFor("GetEntitiesNative"), ["getEntities"]);
  bindings.GetEntitiesNative = GetEntitiesNativeRpcs;
  const GrappleNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<GrappleNative>>(rpcFor("GrappleNative"), ["castRay", "createGrapple", "destroyGrapple", "setGrappleLength", "setGrappleSpringiness"]);
  bindings.GrappleNative = GrappleNativeRpcs;
  const HealNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<HealNative>>(rpcFor("HealNative"), ["healOverTime", "instantHeal"]);
  bindings.HealNative = HealNativeRpcs;
  const IceBlockNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<IceBlockNative>>(rpcFor("IceBlockNative"), ["castIceBlock", "destroyIceBlock", "feedIceBlock", "teardown"]);
  bindings.IceBlockNative = IceBlockNativeRpcs;
  const PingNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<PingNative>>(rpcFor("PingNative"), ["doPing"]);
  bindings.PingNative = PingNativeRpcs;
  const PlayerControlsNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<PlayerControlsNative>>(rpcFor("PlayerControlsNative"), ["jump", "moveHorizontally", "secondaryAttack", "swordSwing"]);
  bindings.PlayerControlsNative = PlayerControlsNativeRpcs;
  const PlayerInventoryNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<PlayerInventoryNative>>(rpcFor("PlayerInventoryNative"), ["activateHotKey", "assignHotKey", "getCoins", "getConsumables", "getEquippedWeapon", "getHotKeyCurrentRow", "getHotKeyMap", "getQuestItems", "hasSword", "setHotKeyCurrentRow"]);
  bindings.PlayerInventoryNative = PlayerInventoryNativeRpcs;
  const ProjectileNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<ProjectileNative>>(rpcFor("ProjectileNative"), ["checkLineOfSight", "createProjectile", "moveProjectileTo", "setProjectileVelocity", "teardown"]);
  bindings.ProjectileNative = ProjectileNativeRpcs;
  const SensorNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<SensorNative>>(rpcFor("SensorNative"), ["createSensor", "registerSensorCallbacks"]);
  bindings.SensorNative = SensorNativeRpcs;
  const SparkNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<SparkNative>>(rpcFor("SparkNative"), ["allocateSparkMana", "createSpark", "destroySpark", "leechFromFountain", "moveSpark", "passMana", "returnSparkToCaster", "setSparkPosition", "teardown", "updateSparkOffset"]);
  bindings.SparkNative = SparkNativeRpcs;
  const SpeedNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<SpeedNative>>(rpcFor("SpeedNative"), ["setSpeed"]);
  bindings.SpeedNative = SpeedNativeRpcs;
  const SpellsNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<SpellsNative>>(rpcFor("SpellsNative"), ["awaitSpell", "get", "getCode", "getEditor", "getSpellLog", "list", "runCode", "runCodeAsync", "runEditor", "runEditorAsync", "runSaved", "runSavedAsync", "save", "setEditor", "stop", "terminateAll"]);
  bindings.SpellsNative = SpellsNativeRpcs;
  const TabsNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<TabsNative>>(rpcFor("TabsNative"), ["closeTab", "maximize", "move", "openTab", "populateEditor", "resize"]);
  bindings.TabsNative = TabsNativeRpcs;
  const TerrainNativeRpcs = bindMethodNamesAsRPCs<GetPromisedRPCTypeSignaturesForClazz<TerrainNative>>(rpcFor("TerrainNative"), ["checkLineOfSight", "queryGrid"]);
  bindings.TerrainNative = TerrainNativeRpcs;
  return bindings;
}
