// AUTO-GENERATED by scripts/ts/generate-auto-module-bindings.ts
// Do not edit manually. Run: npm run generate-auto-module-bindings

import { getAutomaticRPCHandler } from "src/scripting/modules/shared/rpcContract";
import {
  SpellRuntimeModuleCtxAPI,
  SpellRuntimeModuleInstanceNative
} from "src/scripting/runtime/SpellRuntimeAPI";
import AimNative from "src/scripting/modules/auto/Aim.native";
import AirNative from "src/scripting/modules/auto/Air.native";
import AreaPreviewNative from "src/scripting/modules/auto/AreaPreview.native";
import EarthBlockNative from "src/scripting/modules/auto/EarthBlock.native";
import FireNative from "src/scripting/modules/auto/Fire.native";
import GetEntitiesNative from "src/scripting/modules/auto/GetEntities.native";
import GrappleNative from "src/scripting/modules/auto/Grapple.native";
import HealNative from "src/scripting/modules/auto/Heal.native";
import IceBlockNative from "src/scripting/modules/auto/IceBlock.native";
import PingNative from "src/scripting/modules/auto/Ping.native";
import PlayerControlsNative from "src/scripting/modules/auto/PlayerControls.native";
import PlayerInventoryNative from "src/scripting/modules/auto/PlayerInventory.native";
import ProjectileNative from "src/scripting/modules/auto/Projectile.native";
import SensorNative from "src/scripting/modules/auto/Sensor.native";
import SparkNative from "src/scripting/modules/auto/Spark.native";
import SpeedNative from "src/scripting/modules/auto/Speed.native";
import SpellsNative from "src/scripting/modules/auto/Spells.native";
import TabsNative from "src/scripting/modules/auto/Tabs.native";
import TerrainNative from "src/scripting/modules/auto/Terrain.native";

/**
 * Main-thread RPC handler factories, keyed by native module class name.
 * Each instantiates the handler and wraps it with the auto RPC dispatcher.
 */
export const autoNativeBindings: Record<
  string,
  (ctx: SpellRuntimeModuleCtxAPI) => SpellRuntimeModuleInstanceNative
> = {
  AimNative: (ctx) => {
    const handler = new AimNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler),
      teardown: () => handler.teardown()
    };
  },
  AirNative: (ctx) => {
    const handler = new AirNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler)
    };
  },
  AreaPreviewNative: (ctx) => {
    const handler = new AreaPreviewNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler)
    };
  },
  EarthBlockNative: (ctx) => {
    const handler = new EarthBlockNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler),
      teardown: () => handler.teardown()
    };
  },
  FireNative: (ctx) => {
    const handler = new FireNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler)
    };
  },
  GetEntitiesNative: (ctx) => {
    const handler = new GetEntitiesNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler)
    };
  },
  GrappleNative: (ctx) => {
    const handler = new GrappleNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler)
    };
  },
  HealNative: (ctx) => {
    const handler = new HealNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler)
    };
  },
  IceBlockNative: (ctx) => {
    const handler = new IceBlockNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler),
      teardown: () => handler.teardown()
    };
  },
  PingNative: (ctx) => {
    const handler = new PingNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler)
    };
  },
  PlayerControlsNative: (ctx) => {
    const handler = new PlayerControlsNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler)
    };
  },
  PlayerInventoryNative: (ctx) => {
    const handler = new PlayerInventoryNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler)
    };
  },
  ProjectileNative: (ctx) => {
    const handler = new ProjectileNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler),
      teardown: () => handler.teardown()
    };
  },
  SensorNative: (ctx) => {
    const handler = new SensorNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler)
    };
  },
  SparkNative: (ctx) => {
    const handler = new SparkNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler),
      teardown: () => handler.teardown()
    };
  },
  SpeedNative: (ctx) => {
    const handler = new SpeedNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler)
    };
  },
  SpellsNative: (ctx) => {
    const handler = new SpellsNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler)
    };
  },
  TabsNative: (ctx) => {
    const handler = new TabsNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler)
    };
  },
  TerrainNative: (ctx) => {
    const handler = new TerrainNative(ctx);
    return {
      handleDataRPC: getAutomaticRPCHandler(handler)
    };
  }
};
