// AUTO-GENERATED by scripts/ts/generate-auto-module-bindings.ts
// Do not edit manually. Run: npm run generate-auto-module-bindings

import type { SpellApiManifests } from "../core/apiManifest";

/**
 * require()-autocomplete metadata for the auto modules. Spread into
 * SPELL_API_MANIFESTS so each module appears in `require("...")`
 * completion. Inferred stub ⊕ each pseudo module's optional `manifest`.
 */
export const AUTO_SPELL_API_MANIFESTS: SpellApiManifests = {
  aim: {
    description: "Lets the player aim a point with the cursor.",
    export: {
      kind: "object",
      description: "Aim functions and click callbacks.",
      properties: {
        world: {
          kind: "function",
          description: "Resolves to the clicked world position as a Vector.",
          returns: "Vector"
        },
        relative: {
          kind: "function",
          description:
            "Resolves to the clicked position relative to the caster, as a Vector.",
          returns: "Vector"
        },
        asyncRelative: {
          kind: "function",
          description: "Promise variant of relative().",
          returns: "Vector"
        },
        onClick: {
          kind: "function",
          description: "Registers a callback fired on each click.",
          params: [{ name: "cb", type: "function" }]
        },
        offClick: {
          kind: "function",
          description: "Removes a previously registered click callback.",
          params: [{ name: "cb", type: "function" }]
        }
      }
    }
  },
  air: {
    description: "Wind magic — shove entities with an air burst.",
    export: {
      kind: "object",
      description: "Air spell functions.",
      properties: {
        burst: {
          kind: "function",
          description:
            "Applies a wind impulse to a target (or the caster if none given).",
          params: [
            {
              name: "impulse",
              type: "{ x: number, y: number }",
              optional: true
            },
            {
              name: "targetId",
              type: "string | { entityId?: string, handleId?: string }",
              optional: true
            }
          ]
        }
      }
    }
  },
  areaPreview: {
    description: "Draws a translucent polygon overlay in the world.",
    export: {
      kind: "class",
      description:
        "Creates an area-preview overlay from a polygon, optionally attached to an entity.",
      constructorParams: [
        {
          name: "opts",
          type: "{ polygon: ({ x: number, y: number } | [number, number])[], attachToEntityId?: string, color?: { r: number, g: number, b: number } }"
        }
      ],
      properties: {
        id: { kind: "value", valueType: "string" },
        recolor: {
          kind: "function",
          description: "Recolors the preview.",
          params: [
            { name: "r", type: "number" },
            { name: "g", type: "number" },
            { name: "b", type: "number" }
          ]
        },
        destroy: {
          kind: "function",
          description: "Fades the preview away.",
          returns: "void"
        }
      }
    }
  },
  earth: {
    description: "Earth magic — conjure a solid stone block from a shape.",
    export: {
      kind: "class",
      description:
        "Creates an EarthBlock from a polygon, rectangle, circle, or a drawn shape.",
      constructorParams: [
        {
          name: "opts",
          type: "{ shape?: ({ x: number, y: number } | [number, number])[], holes?: ({ x: number, y: number } | [number, number])[][], rect?: { width: number, height: number }, circle?: { radius: number }, angle?: number, offset?: { x: number, y: number } | [number, number], drawShape?: boolean, spark?: { id: string } }",
          optional: true
        }
      ],
      constructorOpts: {
        shape: {
          kind: "value",
          valueType: "({ x: number, y: number } | [number, number])[]",
          description: "Custom polygon outline"
        },
        holes: {
          kind: "value",
          valueType: "({ x: number, y: number } | [number, number])[][]",
          description: "Polygon holes cut from the shape"
        },
        rect: {
          kind: "value",
          valueType: "{ width: number, height: number }"
        },
        circle: { kind: "value", valueType: "{ radius: number }" },
        angle: { kind: "value", valueType: "number" },
        offset: {
          kind: "value",
          valueType: "{ x: number, y: number } | [number, number]"
        },
        drawShape: {
          kind: "value",
          valueType: "boolean",
          description: "Let the player draw the shape with the cursor"
        },
        spark: {
          kind: "value",
          valueType: "{ id: string }",
          description: "ManaSpark to cast from"
        }
      },
      properties: {
        id: { kind: "value", valueType: "string" },
        position: { kind: "value", valueType: "{ x: number, y: number }" },
        destroyed: { kind: "value", valueType: "boolean" },
        destroy: {
          kind: "function",
          description: "Shatters the earth block.",
          returns: "void"
        },
        detachFromTerrain: {
          kind: "function",
          description: "Detaches the block so it can move freely.",
          returns: "boolean"
        }
      }
    }
  },
  fire: {
    description: "Fireball — a fire projectile that can be aimed and detonated.",
    export: {
      kind: "class",
      description:
        "Creates a Fireball projectile from the caster. Also exposes Fire.blast and Fire.wave static spells.",
      constructorParams: [
        {
          name: "opts",
          type: "{ velocity?: { x: number, y: number }, at?: { x: number, y: number }, strength?: number, gravity?: boolean, aim?: boolean, aimSpeed?: number, aimGuide?: boolean, spark?: { id: string } }",
          optional: true
        }
      ],
      constructorOpts: {
        velocity: {
          kind: "value",
          valueType: "{ x: number, y: number }",
          description: "Initial velocity"
        },
        at: {
          kind: "value",
          valueType: "{ x: number, y: number }",
          description: "Fire toward an absolute position"
        },
        strength: {
          kind: "value",
          valueType: "number",
          description: "Damage/mana strength (cost is 5 + strength)"
        },
        gravity: {
          kind: "value",
          valueType: "boolean",
          description: "Whether gravity affects the fireball"
        },
        aim: {
          kind: "value",
          valueType: "boolean",
          description: "Aim the fireball with the cursor"
        },
        aimSpeed: { kind: "value", valueType: "number" },
        aimGuide: { kind: "value", valueType: "boolean" },
        spark: {
          kind: "value",
          valueType: "{ id: string }",
          description: "ManaSpark to cast from"
        }
      },
      properties: {
        id: { kind: "value", valueType: "string" },
        position: { kind: "value", valueType: "{ x: number, y: number }" },
        destroyed: { kind: "value", valueType: "boolean" },
        setVelocity: {
          kind: "function",
          description: "Sets the fireball's velocity.",
          params: [{ name: "velocity", type: "{ x: number, y: number }" }]
        },
        moveTo: {
          kind: "function",
          description:
            "Moves the fireball toward a point; resolves when it arrives.",
          params: [
            { name: "opt", type: "{ x: number, y: number, speed?: number }" }
          ]
        },
        moveToAsync: {
          kind: "function",
          description: "Async/promise variant of moveTo().",
          params: [
            { name: "opt", type: "{ x: number, y: number, speed?: number }" }
          ]
        },
        explode: {
          kind: "function",
          description: "Detonates the fireball into an explosion.",
          returns: "void"
        },
        onImpact: {
          kind: "function",
          description: "Registers a callback fired when the fireball impacts.",
          params: [{ name: "cb", type: "function" }]
        }
      },
      staticProperties: {
        blast: {
          kind: "function",
          description: "Casts a short-range fire blast from the caster.",
          params: [{ name: "arg", type: "boolean | object", optional: true }]
        },
        wave: {
          kind: "function",
          description: "Casts a travelling wave of fire blasts along the ground.",
          params: [{ name: "arg", type: "boolean | object", optional: true }]
        },
        Fireball: { kind: "value", valueType: "class" }
      }
    }
  },
  getEntities: {
    description: "Lists the entities currently in the level.",
    export: {
      kind: "function",
      description:
        "Returns an array of { id, type, position, solid } for every entity in the level. `solid` is true when the entity has a real (non-sensor) physical body.",
      returns:
        "{ id: string, type: string, position: { x: number, y: number }, solid: boolean }[]"
    }
  },
  grapple: {
    description: "Grappling hook — a spring line to a point or entity.",
    export: {
      kind: "class",
      description:
        "Creates a grapple line from the caster to a target point. Also exposes Grapple.castRay.",
      constructorParams: [
        {
          name: "opts",
          type: "{ targetX: number, targetY: number, sourceEntityId?: string, targetEntityId?: string, length?: number, springiness?: number }"
        }
      ],
      properties: {
        id: { kind: "value", valueType: "string" },
        setLength: {
          kind: "function",
          params: [
            { name: "length", type: "number" },
            { name: "transitionMs", type: "number", optional: true }
          ]
        },
        setSpringiness: {
          kind: "function",
          params: [
            { name: "springiness", type: "number" },
            { name: "transitionMs", type: "number", optional: true }
          ]
        },
        detach: { kind: "function", returns: "void" }
      },
      staticProperties: {
        castRay: {
          kind: "function",
          description:
            "Casts a ray from the caster, returning the first terrain/enemy hit.",
          params: [
            {
              name: "opts",
              type: "{ directionX: number, directionY: number, maxDistance?: number }"
            }
          ],
          returns:
            "{ hit: boolean, x: number, y: number, distance: number, entityId?: string }"
        },
        Grapple: { kind: "value", valueType: "class" }
      }
    }
  },
  heal: {
    description: "Nature magic — restore health, instantly or over time.",
    export: {
      kind: "class",
      description:
        "Heal spell. Use the static Heal.instant / Heal.overTime spells (castable via spark.cast).",
      constructorParams: [
        {
          name: "opts",
          type: "{ targetId?: string, strength?: number }",
          optional: true
        }
      ],
      properties: {},
      staticProperties: {
        instant: {
          kind: "function",
          description: "Instantly heals the target (or caster).",
          params: [{ name: "opts", type: "{ strength?: number }" }]
        },
        overTime: {
          kind: "function",
          description: "Heals the target over several seconds.",
          params: [{ name: "opts", type: "{ strength?: number }" }]
        },
        Heal: { kind: "value", valueType: "class" }
      }
    }
  },
  ice: {
    description: "Ice magic — conjure a solid ice block from a shape.",
    export: {
      kind: "class",
      description:
        "Creates an IceBlock from a polygon, rectangle, or circle in front of the caster.",
      constructorParams: [
        {
          name: "opts",
          type: "{ shape?: ({ x: number, y: number } | [number, number])[], rect?: { width: number, height: number }, circle?: { radius: number }, angle?: number, spark?: { id: string } }",
          optional: true
        }
      ],
      constructorOpts: {
        shape: {
          kind: "value",
          valueType: "({ x: number, y: number } | [number, number])[]",
          description: "Custom polygon outline"
        },
        rect: {
          kind: "value",
          valueType: "{ width: number, height: number }",
          description: "Rectangle shape"
        },
        circle: {
          kind: "value",
          valueType: "{ radius: number }",
          description: "Circle shape"
        },
        angle: { kind: "value", valueType: "number" },
        spark: {
          kind: "value",
          valueType: "{ id: string }",
          description: "ManaSpark to cast from"
        }
      },
      properties: {
        id: { kind: "value", valueType: "string" },
        position: { kind: "value", valueType: "{ x: number, y: number }" },
        destroyed: { kind: "value", valueType: "boolean" },
        mana: {
          kind: "value",
          valueType: "number"
        },
        storeMana: {
          kind: "function",
          description:
            "Transfers mana from the caster into the ice block. Stored mana is spent to resist melting, keeping the block frozen longer.",
          returns: "void"
        },
        destroy: {
          kind: "function",
          description: "Shrinks and removes the ice block.",
          returns: "void"
        }
      }
    }
  },
  ping: {
    description: "Pings the area around the caster to detect entities.",
    export: {
      kind: "function",
      description:
        "Emits a ping from the caster and resolves to the entities it detected.",
      returns: "Entity[]"
    }
  },
  playerControls: {
    description: "Drives the player's controls (jump, move, attack).",
    export: {
      kind: "object",
      description: "Functions that emit player control events.",
      properties: {
        jump: { kind: "function", description: "Makes the player jump." },
        moveHorizontally: {
          kind: "function",
          description: "Moves the player horizontally (-1 left, 1 right).",
          params: [{ name: "direction", type: "number" }]
        },
        secondaryAttack: {
          kind: "function",
          description: "Triggers the player's secondary attack."
        },
        swordSwing: {
          kind: "function",
          description: "Triggers a sword swing."
        }
      }
    }
  },
  playerInventory: {
    description: "Reads and manipulates the player's inventory and hotkeys.",
    export: {
      kind: "object",
      description: "Inventory query and hotkey command functions.",
      properties: {
        getEquippedWeapon: { kind: "function", returns: "string | null" },
        getHotKeyMap: { kind: "function", returns: "object" },
        getHotKeyCurrentRow: { kind: "function", returns: "number" },
        getConsumables: { kind: "function", returns: "object" },
        getQuestItems: { kind: "function", returns: "object" },
        hasSword: { kind: "function", returns: "boolean" },
        getCoins: { kind: "function", returns: "number" },
        setHotKeyCurrentRow: {
          kind: "function",
          params: [{ name: "row", type: "number" }]
        },
        assignHotKey: {
          kind: "function",
          params: [
            { name: "hotKey", type: "string" },
            { name: "assignment", type: "object | null" }
          ]
        },
        activateHotKey: {
          kind: "function",
          params: [{ name: "hotKey", type: "string" }]
        }
      }
    }
  },
  projectile: {
    description: "A configurable projectile with optional homing/steering.",
    export: {
      kind: "class",
      description:
        "Creates a generic projectile from the caster, with configurable element, color, gravity, and trail.",
      constructorParams: [
        {
          name: "opts",
          type: "{ velocity?: { x: number, y: number }, strength?: number, aim?: boolean, aimSpeed?: number, aimGuide?: boolean, directPath?: boolean, gravity?: number, radius?: number, elementalType?: string, damageType?: string, colorInner?: { r: number, g: number, b: number }, colorOuter?: { r: number, g: number, b: number }, spark?: { id: string } }",
          optional: true
        }
      ],
      constructorOpts: {
        velocity: {
          kind: "value",
          valueType: "{ x: number, y: number }",
          description: "Initial velocity"
        },
        strength: {
          kind: "value",
          valueType: "number",
          description: "Damage/mana strength"
        },
        aim: { kind: "value", valueType: "boolean" },
        aimSpeed: { kind: "value", valueType: "number" },
        aimGuide: { kind: "value", valueType: "boolean" },
        directPath: { kind: "value", valueType: "boolean" },
        gravity: {
          kind: "value",
          valueType: "number",
          description: "Gravity coefficient (0 = none)"
        },
        radius: { kind: "value", valueType: "number" },
        elementalType: { kind: "value", valueType: "string" },
        damageType: { kind: "value", valueType: "string" },
        colorInner: {
          kind: "value",
          valueType: "{ r: number, g: number, b: number }"
        },
        colorOuter: {
          kind: "value",
          valueType: "{ r: number, g: number, b: number }"
        },
        spark: {
          kind: "value",
          valueType: "{ id: string }",
          description: "ManaSpark to cast from"
        }
      },
      properties: {
        id: { kind: "value", valueType: "string" },
        position: { kind: "value", valueType: "{ x: number, y: number }" },
        destroyed: { kind: "value", valueType: "boolean" },
        setVelocity: {
          kind: "function",
          description: "Sets the projectile's velocity.",
          params: [{ name: "velocity", type: "{ x: number, y: number }" }]
        },
        moveTo: {
          kind: "function",
          description:
            "Moves the projectile toward a point; resolves when it arrives.",
          params: [
            { name: "opt", type: "{ x: number, y: number, speed?: number }" }
          ]
        },
        moveToAsync: {
          kind: "function",
          description: "Async/promise variant of moveTo().",
          params: [
            { name: "opt", type: "{ x: number, y: number, speed?: number }" }
          ]
        },
        canMoveTo: {
          kind: "function",
          description:
            "Returns whether the projectile has line of sight to a point.",
          params: [{ name: "opt", type: "{ x: number, y: number }" }],
          returns: "boolean"
        }
      },
      staticProperties: {
        Projectile: { kind: "value", valueType: "class" }
      }
    }
  },
  sensor: {
    description: "Detects entities within a radius of the caster.",
    export: {
      kind: "class",
      description:
        "Creates a sensor that follows the caster and reports nearby entities, with enter/leave callbacks.",
      constructorParams: [
        {
          name: "opts",
          type: "{ radius?: number, spark?: { id: string } }",
          optional: true
        }
      ],
      constructorOpts: {
        radius: {
          kind: "value",
          valueType: "number",
          description: "Detection radius in world units"
        },
        spark: {
          kind: "value",
          valueType: "{ id: string }",
          description: "ManaSpark to attach the sensor to"
        }
      },
      properties: {
        id: { kind: "value", valueType: "string" },
        ready: { kind: "value", valueType: "boolean" },
        position: { kind: "value", valueType: "{ x: number, y: number }" },
        destroyed: { kind: "value", valueType: "boolean" },
        entities: {
          kind: "value",
          valueType: "Entity[]",
          description: "Entities currently inside the sensor"
        },
        onEntityEnter: {
          kind: "function",
          description: "Registers a callback fired when an entity enters.",
          params: [{ name: "cb", type: "function" }]
        },
        onEntityLeave: {
          kind: "function",
          description: "Registers a callback fired when an entity leaves.",
          params: [{ name: "cb", type: "function" }]
        }
      }
    }
  },
  spark: {
    description: "ManaSpark — a floating orb that casts spells.",
    export: {
      kind: "class",
      description:
        "Creates a ManaSpark entity that orbits the caster and can cast spells from its position.",
      constructorParams: [
        {
          name: "opts",
          type: "{ mana?: number, offset?: { x: number, y: number }, cameraFollow?: boolean, casterId?: string }",
          optional: true
        }
      ],
      constructorOpts: {
        mana: {
          kind: "value",
          valueType: "number",
          description: "Initial mana to transfer into the spark"
        },
        offset: {
          kind: "value",
          valueType: "{ x: number, y: number }",
          description: "Position offset relative to the caster"
        },
        cameraFollow: {
          kind: "value",
          valueType: "boolean",
          description: "Should the camera follow this spark?"
        },
        casterId: {
          kind: "value",
          valueType: "string",
          description: "ID of the entity to cast from (defaults to the caster)"
        }
      },
      properties: {
        id: {
          kind: "value",
          valueType: "string",
          description: "Persistent handle ID"
        },
        type: {
          kind: "value",
          valueType: "string",
          description: "Entity type string ('ManaSpark')"
        },
        mana: {
          kind: "value",
          valueType: "number",
          description: "Current mana held by the spark"
        },
        cast: {
          kind: "function",
          description:
            "Casts a spell or constructs a class from this spark's position.",
          params: [
            { name: "spell", type: "class | function" },
            { name: "arg", type: "object", optional: true }
          ]
        },
        castAsync: {
          kind: "function",
          description: "Async/promise variant of cast().",
          params: [
            { name: "spell", type: "class | function" },
            { name: "arg", type: "object", optional: true }
          ]
        },
        destroy: {
          kind: "function",
          description: "Destroys this spark.",
          returns: "void"
        },
        setOffset: {
          kind: "function",
          description:
            "Updates the spark's orbit offset relative to the caster.",
          params: [{ name: "offset", type: "{ x: number, y: number }" }]
        },
        setPosition: {
          kind: "function",
          description: "Teleports the spark toward an absolute position.",
          params: [{ name: "position", type: "{ x: number, y: number }" }]
        },
        returnToCaster: {
          kind: "function",
          description:
            "Streams the spark's mana back to the caster and destroys it.",
          returns: "void"
        },
        storeMana: {
          kind: "function",
          description: "Transfers mana from the caster into this spark.",
          params: [{ name: "amount", type: "number" }]
        },
        leech: {
          kind: "function",
          description:
            "Drains a nearby ManaFountain (within range, line of sight) to refill the spark.",
          params: [{ name: "fountainHandleId", type: "string" }]
        },
        passMana: {
          kind: "function",
          description: "Streams mana from this spark to another spark.",
          params: [
            { name: "targetSpark", type: "ManaSpark" },
            { name: "amount", type: "number" }
          ]
        },
        moveRight: {
          kind: "function",
          description: "Moves the spark right by n tiles (default 1).",
          params: [{ name: "n", type: "number", optional: true }]
        },
        moveLeft: {
          kind: "function",
          description: "Moves the spark left by n tiles (default 1).",
          params: [{ name: "n", type: "number", optional: true }]
        },
        moveUp: {
          kind: "function",
          description: "Moves the spark up by n tiles (default 1).",
          params: [{ name: "n", type: "number", optional: true }]
        },
        moveDown: {
          kind: "function",
          description: "Moves the spark down by n tiles (default 1).",
          params: [{ name: "n", type: "number", optional: true }]
        }
      }
    }
  },
  speed: {
    description: "Controls how fast the spell interpreter executes.",
    export: {
      kind: "function",
      description: "Sets the interpreter execution speed (clamped 0.001–100).",
      params: [{ name: "speed", type: "number" }]
    }
  },
  spells: {
    description: "Inspect, edit, save, and run other spells as sub-spells.",
    export: {
      kind: "class",
      description: "Spell library and sub-spell runner.",
      properties: {},
      staticProperties: {
        list: { kind: "function", description: "Lists saved spells.", returns: "object[]" },
        get: { kind: "function", description: "Gets a saved spell's details.", params: [{ name: "name", type: "string" }] },
        getCode: { kind: "function", description: "Gets a saved spell's code.", params: [{ name: "name", type: "string" }], returns: "string" },
        save: { kind: "function", description: "Saves (or updates) a spell.", params: [{ name: "name", type: "string" }, { name: "code", type: "string" }] },
        setEditor: { kind: "function", description: "Sets a code editor tab's contents.", params: [{ name: "code", type: "string" }, { name: "tabId", type: "string", optional: true }] },
        getEditor: { kind: "function", description: "Gets a code editor tab's contents.", params: [{ name: "tabId", type: "string", optional: true }], returns: "string" },
        runCode: { kind: "function", description: "Runs code as a sub-spell (blocks until done).", params: [{ name: "code", type: "string" }] },
        runSaved: { kind: "function", description: "Runs a saved spell (blocks until done).", params: [{ name: "name", type: "string" }] },
        runEditor: { kind: "function", description: "Runs an editor tab's code (blocks until done).", params: [{ name: "tabId", type: "string", optional: true }] },
        stop: { kind: "function", description: "Stops a running sub-spell by context id.", params: [{ name: "contextId", type: "string" }] },
        terminateAll: { kind: "function", description: "Terminates all running spells." },
        runCodeAsync: { kind: "function", description: "Runs code as a sub-spell, returns a RunningSpell handle.", params: [{ name: "code", type: "string" }], returns: "RunningSpell" },
        runSavedAsync: { kind: "function", description: "Runs a saved spell, returns a RunningSpell handle.", params: [{ name: "name", type: "string" }], returns: "RunningSpell" },
        runEditorAsync: { kind: "function", description: "Runs an editor tab's code, returns a RunningSpell handle.", params: [{ name: "tabId", type: "string", optional: true }], returns: "RunningSpell" }
      }
    }
  },
  tabs: {
    description: "Open, close, move, and resize UI panels (tabs).",
    export: {
      kind: "class",
      description: "Layout/tab control functions.",
      properties: {},
      staticProperties: {
        openTab: {
          kind: "function",
          description: "Opens a UI panel by component name; returns its tab id.",
          params: [{ name: "componentName", type: "string" }],
          returns: "string"
        },
        closeTab: {
          kind: "function",
          description: "Closes tabs by component name or a specific tab id.",
          params: [{ name: "nameOrId", type: "string" }]
        },
        populateEditor: {
          kind: "function",
          description: "Sets the code of a code-editor tab.",
          params: [
            { name: "tabId", type: "string" },
            { name: "contents", type: "string" }
          ]
        },
        maximize: {
          kind: "function",
          description: "Toggles maximize on the tabset containing a tab.",
          params: [{ name: "tabId", type: "string" }]
        },
        resize: {
          kind: "function",
          description: "Resizes a tab's tabset (weight 0-1 relative to siblings).",
          params: [
            { name: "tabId", type: "string" },
            { name: "weight", type: "number" }
          ]
        },
        move: {
          kind: "function",
          description:
            "Moves a tab to a position (left/right/top/bottom); returns new tab id.",
          params: [
            { name: "tabId", type: "string" },
            { name: "position", type: "string" }
          ],
          returns: "string"
        }
      }
    }
  },
  terrain: {
    description: "Query terrain — line of sight and nav-grid sampling.",
    export: {
      kind: "object",
      description: "Terrain query functions.",
      properties: {
        checkLineOfSight: {
          kind: "function",
          description:
            "Returns whether terrain blocks the line between two points.",
          params: [
            {
              name: "opts",
              type: "{ from: { x: number, y: number }, to: { x: number, y: number }, ignoreEntities?: boolean }"
            }
          ],
          returns: "boolean"
        },
        queryGrid: {
          kind: "function",
          description:
            "Samples the nav-grid over a region, returning a 2D block grid.",
          params: [
            {
              name: "opts",
              type: "{ min: { x: number, y: number }, max: { x: number, y: number }, relative?: boolean }"
            }
          ],
          returns: "{ grid: number[][], resolution: number }"
        }
      }
    }
  },
  info: {
    description: "Inspects an imported module or entity, listing its available properties.",
    export: {
      kind: "function",
      description:
        "Returns a description of the target's properties/methods (for discovery).",
      params: [{ name: "target", type: "any" }],
      returns: "object"
    }
  },
  self: {
    description: "The entity casting this spell.",
    export: {
      kind: "value",
      valueType: "Entity",
      description: "The caster entity (id, type, position, ...)."
    }
  },
  shapes: {
    description: "Helpers that build polygon outlines (for earth/ice shapes).",
    export: {
      kind: "class",
      description: "Shape-builder functions returning Vector[] outlines.",
      properties: {},
      staticProperties: {
        rect: {
          kind: "function",
          params: [
            { name: "width", type: "number" },
            { name: "height", type: "number" }
          ],
          returns: "Vector[]"
        },
        triangle: {
          kind: "function",
          params: [
            { name: "radius", type: "number" },
            { name: "angle", type: "number", optional: true }
          ],
          returns: "Vector[]"
        },
        circle: {
          kind: "function",
          params: [
            { name: "radius", type: "number" },
            { name: "count", type: "number", optional: true }
          ],
          returns: "Vector[]"
        }
      }
    }
  },
  vector: {
    description: "2D vector with chainable math helpers.",
    export: {
      kind: "class",
      description:
        "Creates a 2D vector. Accepts (x, y), an [x, y] array, or a { x, y } object.",
      constructorParams: [
        { name: "xOrObj", type: "number | [number, number] | { x: number, y: number }", optional: true },
        { name: "y", type: "number", optional: true }
      ],
      properties: {
        x: { kind: "value", valueType: "number" },
        y: { kind: "value", valueType: "number" },
        clone: { kind: "function", returns: "Vector" },
        add: {
          kind: "function",
          params: [{ name: "other", type: "{ x: number, y: number }" }],
          returns: "Vector"
        },
        sub: {
          kind: "function",
          params: [{ name: "other", type: "{ x: number, y: number }" }],
          returns: "Vector"
        },
        scale: {
          kind: "function",
          params: [{ name: "scale", type: "number" }],
          returns: "Vector"
        },
        rotate: {
          kind: "function",
          params: [{ name: "rotation", type: "number" }],
          returns: "Vector"
        },
        length: { kind: "function", returns: "number" },
        dot: {
          kind: "function",
          params: [{ name: "other", type: "{ x: number, y: number }" }],
          returns: "number"
        },
        normalize: { kind: "function", returns: "Vector" },
        angle: { kind: "function", returns: "number" },
        round: {
          kind: "function",
          params: [{ name: "radix", type: "number", optional: true }],
          returns: "Vector"
        }
      }
    }
  },
  wait: {
    description: "Pauses spell execution without blocking the game loop.",
    export: {
      kind: "function",
      description: "Waits for the given milliseconds (default 1000).",
      params: [{ name: "ms", type: "number" }],
      properties: {
        async: {
          kind: "function",
          description: "Promise-based variant for use inside async functions.",
          params: [{ name: "ms", type: "number" }]
        }
      }
    }
  }
};
