export type sprite_layers =
  | "Phase 1"
  | "reference"
  | "top-wings"
  | "bottom-shield"
  | "back-hair"
  | "bottom-wings"
  | "tail"
  | "right-keg"
  | "left_leg"
  | "pelvis"
  | "leg-cover"
  | "abs"
  | "arm"
  | "back_shoulder"
  | "shoulder"
  | "hair"
  | "head"
  | "Antenaes"
  | "Shield"
  | "shield_light"
  | "sword"
  | "smears_and_effects";
export type sprite_animations =
  | "new_walk"
  | "idle_3"
  | "attack_new"
  | "anticipation_frame_01"
  | "anticipation_frame_02"
  | "jump"
  | "Shield_charge"
  | "charge"
  | "dazed"
  | "Shield_new"
  | "parry_new"
  | "hurt_1"
  | "hurt_2";
